"use client";

import { useEffect, useState } from "react";

type Data = { settings: { attendance_verification_enabled: boolean; attendance_verification_organizers_only: boolean }; metrics: { verified: number; presencial: number; virtual: number; pending: number; tests: number } };
export default function AttendanceControl() {
  const [data, setData] = useState<Data | null>(null); const [saving, setSaving] = useState(false);
  async function load() { const response = await fetch("/api/admin/attendance", { cache: "no-store" }); if (response.ok) setData(await response.json()); }
  useEffect(() => { const kickoff = window.setTimeout(() => void load(), 0); const timer = window.setInterval(() => void load(), 30000); return () => { window.clearTimeout(kickoff); window.clearInterval(timer); }; }, []);
  async function update(changes: Record<string, unknown>) { setSaving(true); const response = await fetch("/api/admin/attendance", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(changes) }); setSaving(false); if (response.ok) await load(); }
  async function clearTests() { if (!window.confirm("¿Borrar las asistencias registradas durante las pruebas?")) return; await update({ action: "clearTests" }); }
  const metrics = data?.metrics;
  const enabled = Boolean(data?.settings.attendance_verification_enabled);
  const organizersOnly = Boolean(data?.settings.attendance_verification_organizers_only);
  return <div className="admin-content attendance-control"><div className="panel"><p className="admin-kicker">DÍA DEL EVENTO</p><h2>Verificación de asistencia</h2><p>Actívala cuando inicie el control de asistencia. Los organizadores podrán verificar a las personas presenciales desde su cuenta y las virtuales confirmarán su presencia desde la suya.</p><label className="live-toggle large"><div><b>{enabled ? "Verificación habilitada" : "Verificación cerrada"}</b><small>{enabled ? (organizersOnly ? "Solo el equipo organizador puede verificar; los participantes no ven el módulo." : "Ya se registran asistencias y quedarán habilitados los diplomas correspondientes.") : "Nadie puede confirmarse todavía."}</small></div><input type="checkbox" disabled={saving} checked={enabled} onChange={event => update({ attendanceEnabled: event.target.checked })} /><i /></label><label className="live-toggle"><div><b>Modo de pruebas (solo organizadores)</b><small>{organizersOnly ? "El módulo aparece únicamente a quienes tengan el rol de organizador. El kiosko solo encuentra a organizadores y ningún diploma se habilita." : "Desactívalo el día del evento para abrir la verificación a todos los inscritos."}</small></div><input type="checkbox" disabled={saving} checked={organizersOnly} onChange={event => update({ organizersOnly: event.target.checked })} /><i /></label>{Boolean(metrics?.tests) && <p className="admin-note">Hay {metrics?.tests} asistencia{metrics?.tests === 1 ? "" : "s"} registrada{metrics?.tests === 1 ? "" : "s"} en pruebas. <button className="danger-link" disabled={saving} onClick={clearTests}>Borrar registros de prueba</button></p>}</div><div className="stat-grid"><article><span>Asistencias verificadas</span><b>{metrics?.verified ?? 0}</b><small>En tiempo real</small></article><article><span>Presenciales</span><b>{metrics?.presencial ?? 0}</b><small>Verificadas por organización</small></article><article><span>Virtuales</span><b>{metrics?.virtual ?? 0}</b><small>Confirmadas desde su cuenta</small></article><article><span>Pendientes</span><b>{metrics?.pending ?? 0}</b><small>Inscripciones confirmadas</small></article></div></div>;
}
