"use client";
import { ChangeEvent, useEffect, useState } from "react";
type Sponsor = { id:number; name:string; description:string|null; website:string|null; logo_url:string|null; display_order:number; is_published:boolean };
type SponsorDraft = Partial<Sponsor> & { name:string; description:string; website:string; logo_url:string; display_order:number; is_published:boolean };
const blank: SponsorDraft = { name:"",description:"",website:"",logo_url:"",display_order:0,is_published:true };
export default function SponsorManager() { const [items,setItems]=useState<Sponsor[]>([]); const [draft,setDraft]=useState<SponsorDraft>(blank); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/admin/sponsors");if(r.ok)setItems((await r.json()).sponsors)} useEffect(()=>{const kickoff=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(kickoff)},[]);
 async function upload(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setSaving(true);const fd=new FormData();fd.append("file",f);fd.append("purpose","sponsor");const r=await fetch("/api/admin/media",{method:"POST",body:fd});const d=await r.json();setSaving(false);if(r.ok)setDraft({...draft,logo_url:d.url});else setMessage(d.error??"No se pudo cargar el logo.")}
 async function save(){if(!draft.name.trim()){setMessage("Escribe el nombre del patrocinador.");return}setSaving(true);const method=draft.id?"PATCH":"POST";const r=await fetch("/api/admin/sponsors",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const d=await r.json();setSaving(false);if(!r.ok){setMessage(d.error??"No se pudo guardar.");return}setDraft(blank);setMessage("Patrocinador guardado.");await load()}
 async function remove(id:number){if(!window.confirm("¿Eliminar este patrocinador?"))return;await fetch(`/api/admin/sponsors?id=${id}`,{method:"DELETE"});if(draft.id===id)setDraft(blank);await load()}
 return <div className="admin-content sponsor-manager"><div className="sponsor-admin-layout"><aside className="panel sponsor-list"><div className="panel-title"><h3>Patrocinadores</h3><button onClick={()=>setDraft({...blank,display_order:items.length+1})}>+ Nuevo</button></div>{items.length?items.map(item=><button key={item.id} className={draft.id===item.id?"selected":""} onClick={()=>setDraft({...item,description:item.description??"",website:item.website??"",logo_url:item.logo_url??""})}>{item.logo_url?<img src={item.logo_url} alt=""/>:<span>{item.name.slice(0,1)}</span>}<div><b>{item.name}</b><small>{item.is_published?"Visible":"Oculto"}</small></div></button>):<div className="admin-empty"><b>Aún no hay patrocinadores.</b><p>Agrega el primero cuando esté confirmado.</p></div>}</aside><section className="panel sponsor-editor"><div className="panel-title"><h3>{draft.id?"Editar patrocinador":"Nuevo patrocinador"}</h3>{draft.id&&<button className="danger-link" onClick={()=>{if(draft.id)remove(draft.id)}}>Eliminar</button>}</div><div className="speaker-form-grid"><label>Nombre *<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Orden de aparición<input type="number" min="0" value={draft.display_order} onChange={e=>setDraft({...draft,display_order:Number(e.target.value)})}/></label><label className="wide">Descripción breve<textarea rows={3} value={draft.description??""} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="wide">Sitio web<input placeholder="https://..." value={draft.website??""} onChange={e=>setDraft({...draft,website:e.target.value})}/></label></div><label className="media-upload sponsor-logo-upload"><b>Logo del patrocinador</b>{draft.logo_url?<img src={draft.logo_url} alt="Vista previa del logo"/>:<small>PNG, JPG o WebP</small>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload}/><span>{saving?"Cargando…":"Cargar o reemplazar logo"}</span></label><label className="publish-check"><input type="checkbox" checked={draft.is_published} onChange={e=>setDraft({...draft,is_published:e.target.checked})}/><span><b>Mostrar en la página principal</b><small>El logo, nombre y enlace se verán en la sección de aliados.</small></span></label><button className="admin-save" disabled={saving} onClick={save}>{saving?"Guardando…":"Guardar patrocinador"}</button>{message&&<p className="community-success">{message}</p>}</section></div></div> }
