import { isEventAdmin } from "../../../../lib/admin";
import { supabaseServerFetch } from "../../../../lib/supabase-server";
const fields = "id,name,description,website,logo_url,display_order,is_published,created_at,updated_at";
const clean = (value: unknown, limit = 500) => String(value ?? "").trim().slice(0, limit);
export async function GET() { if (!await isEventAdmin()) return Response.json({ error: "No autorizado" }, { status: 401 }); const response = await supabaseServerFetch(`encuentro_psicologico_sponsors?select=${fields}&order=display_order.asc,id.asc`); return response.ok ? Response.json({ sponsors: await response.json() }) : Response.json({ error: "No se pudieron cargar los patrocinadores." }, { status: 503 }); }
function payload(body: Record<string, unknown>) { return { name: clean(body.name, 130), description: clean(body.description, 500) || null, website: clean(body.website, 500) || null, logo_url: clean(body.logo_url, 800) || null, display_order: Math.max(0, Number(body.display_order) || 0), is_published: Boolean(body.is_published), updated_at: new Date().toISOString() }; }
export async function POST(request: Request) { if (!await isEventAdmin()) return Response.json({ error: "No autorizado" }, { status: 401 }); const data = payload(await request.json()); if (!data.name) return Response.json({ error: "Escribe el nombre del patrocinador." }, { status: 400 }); const response = await supabaseServerFetch(`encuentro_psicologico_sponsors?select=${fields}`, { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(data) }); return response.ok ? Response.json({ sponsor: (await response.json())[0] }) : Response.json({ error: "No se pudo crear el patrocinador." }, { status: 503 }); }
export async function PATCH(request: Request) { if (!await isEventAdmin()) return Response.json({ error: "No autorizado" }, { status: 401 }); const body = await request.json() as Record<string, unknown>; const id = Number(body.id); const data = payload(body); if (!id || !data.name) return Response.json({ error: "Completa el nombre del patrocinador." }, { status: 400 }); const response = await supabaseServerFetch(`encuentro_psicologico_sponsors?id=eq.${id}&select=${fields}`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(data) }); return response.ok ? Response.json({ sponsor: (await response.json())[0] }) : Response.json({ error: "No se pudo actualizar el patrocinador." }, { status: 503 }); }
export async function DELETE(request: Request) { if (!await isEventAdmin()) return Response.json({ error: "No autorizado" }, { status: 401 }); const id = Number(new URL(request.url).searchParams.get("id")); if (!id) return Response.json({ error: "Patrocinador no válido." }, { status: 400 }); const response = await supabaseServerFetch(`encuentro_psicologico_sponsors?id=eq.${id}`, { method: "DELETE" }); return response.ok ? Response.json({ ok: true }) : Response.json({ error: "No se pudo eliminar el patrocinador." }, { status: 503 }); }
