-- Rifas de souvenirs durante la jornada.
-- El sorteo se hace desde el centro de control y guarda el registro de cada
-- ganador: así nadie sale dos veces por error y queda constancia de qué se
-- entregó, a quién y cuándo.
create table if not exists public.encuentro_psicologico_raffles (
  id bigint generated by default as identity primary key,
  prize text not null,
  scope text not null default 'presencial',
  registration_id bigint not null references public.encuentro_psicologico_registrations(id) on delete cascade,
  winner_name text not null,
  winner_license text,
  winner_institution text,
  winner_modality text,
  delivered_at timestamptz,
  drawn_by uuid,
  created_at timestamptz not null default now(),
  constraint encuentro_psicologico_raffles_prize_length
    check (char_length(trim(prize)) between 2 and 120),
  constraint encuentro_psicologico_raffles_scope
    check (scope in ('all', 'presencial', 'verified'))
);

create index if not exists encuentro_psicologico_raffles_created_idx
  on public.encuentro_psicologico_raffles (created_at desc);

create index if not exists encuentro_psicologico_raffles_registration_idx
  on public.encuentro_psicologico_raffles (registration_id);

alter table public.encuentro_psicologico_raffles enable row level security;
revoke all on public.encuentro_psicologico_raffles from anon, authenticated;
grant all on public.encuentro_psicologico_raffles to service_role;
grant usage, select on sequence public.encuentro_psicologico_raffles_id_seq to service_role;
