create table if not exists public.encuentro_psicologico_program (
  id bigint generated by default as identity primary key,
  start_time text not null default '',
  end_time text not null default '',
  type text not null default '',
  title text not null,
  description text not null default '',
  details text not null default '',
  display_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint encuentro_psicologico_program_title_length check (char_length(title) between 2 and 180),
  constraint encuentro_psicologico_program_order_nonnegative check (display_order >= 0)
);

alter table public.encuentro_psicologico_program enable row level security;
drop policy if exists "encuentro_psicologico_program_server_only" on public.encuentro_psicologico_program;
create policy "encuentro_psicologico_program_server_only"
  on public.encuentro_psicologico_program for all to anon, authenticated
  using (false) with check (false);
revoke all on table public.encuentro_psicologico_program from anon, authenticated;
grant all on table public.encuentro_psicologico_program to service_role;
grant usage, select on sequence public.encuentro_psicologico_program_id_seq to service_role;

insert into public.encuentro_psicologico_program
  (start_time, end_time, type, title, description, details, display_order, is_published)
select *
from (values
  ('8:30', '9:00', 'Registro', 'Registro e inscripciones', 'Recepción de participantes', 'Ingreso, verificación de inscripción y ubicación de participantes.', 1, true),
  ('9:00', '9:10', 'Apertura', 'Apertura institucional', 'Bienvenida a la jornada', 'Palabras de bienvenida, encuadre académico y presentación general de la jornada.', 2, true),
  ('9:10', '9:30', 'Charla 1', 'Diagnóstico', 'Duelo normal vs. trastorno de duelo prolongado · DSM-5-TR / CIE-11', 'Criterios clínicos, señales de alarma y diagnóstico diferencial.', 3, true),
  ('9:30', '9:50', 'Charla 2', 'Impacto corporal', 'Somatización del duelo no resuelto', 'Manifestaciones corporales y lectura clínica del impacto del duelo detenido.', 4, true),
  ('9:50', '10:10', 'Charla 3', 'Manejo terapéutico', 'Intervención clínica individual', 'Recursos de intervención y acompañamiento psicoterapéutico.', 5, true),
  ('10:10', '10:25', 'Receso', 'Coffee break', 'Pausa y encuentro', 'Coffee break para participantes presenciales y pausa técnica para participantes virtuales.', 6, true),
  ('10:25', '10:45', 'Charla 4', 'Manejo familiar', 'El sistema familiar frente al duelo detenido', 'Dinámicas familiares, recursos de apoyo y abordaje sistémico.', 7, true),
  ('10:45', '11:05', 'Charla 5', 'Psiquiatría', 'Cuándo se requiere manejo farmacológico', 'Criterios de referencia, manejo interdisciplinario y acompañamiento médico.', 8, true),
  ('11:05', '11:25', 'Charla 6', 'Cierre comunitario', 'Resiliencia y rol del psicólogo local', 'Cierre comunitario, mirada local y continuidad del acompañamiento.', 9, true),
  ('11:25', '12:00', 'Cierre', 'Panel de preguntas y entrega de constancias', 'Conversación con los 6 ponentes · cierre institucional', 'Panel integrador, preguntas del público, cierre institucional y entrega de constancias.', 10, true)
) as defaults(start_time, end_time, type, title, description, details, display_order, is_published)
where not exists (select 1 from public.encuentro_psicologico_program);

alter table public.encuentro_psicologico_speakers
  add column if not exists program_item_id bigint references public.encuentro_psicologico_program(id) on delete set null,
  add column if not exists contact_email text not null default '',
  add column if not exists contact_phone text not null default '',
  add column if not exists contact_website text not null default '';

create index if not exists encuentro_psicologico_speakers_program_item_idx
  on public.encuentro_psicologico_speakers(program_item_id);

grant all on table public.encuentro_psicologico_speakers to service_role;
