-- Supabase Auth and participant portal isolation for Encuentro Psicologico.
alter table public.encuentro_psicologico_registrations add column if not exists user_id uuid references auth.users(id) on delete set null;
create unique index if not exists encuentro_psicologico_registration_user_modality_idx on public.encuentro_psicologico_registrations(user_id, modality) where user_id is not null;

create table if not exists public.encuentro_psicologico_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null, phone text not null, attendee_type text not null default 'general',
  profession text, license text, institution text, country text not null default 'Guatemala',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table public.encuentro_psicologico_profiles enable row level security;
revoke all on public.encuentro_psicologico_profiles from anon, authenticated;
grant all on public.encuentro_psicologico_profiles to service_role;

create table if not exists public.encuentro_psicologico_resources (
  id bigint generated by default as identity primary key, title text not null, description text,
  file_url text, is_published boolean not null default false, created_at timestamptz not null default now()
);
alter table public.encuentro_psicologico_resources enable row level security;
revoke all on public.encuentro_psicologico_resources from anon, authenticated;
grant all on public.encuentro_psicologico_resources to service_role;

create table if not exists public.encuentro_psicologico_certificates (
  user_id uuid primary key references auth.users(id) on delete cascade, certificate_number text unique,
  attendance_confirmed boolean not null default false, issued_at timestamptz, updated_at timestamptz not null default now()
);
alter table public.encuentro_psicologico_certificates enable row level security;
revoke all on public.encuentro_psicologico_certificates from anon, authenticated;
grant all on public.encuentro_psicologico_certificates to service_role;

-- The deployed function also receives p_user_id, links registrations to Auth,
-- upserts the participant profile and prepares the certificate record atomically.
