create table if not exists public.encuentro_psicologico_speaker_materials (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  program_item_id bigint not null references public.encuentro_psicologico_program(id) on delete cascade,
  title text not null,
  description text,
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  size_bytes bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint encuentro_psicologico_speaker_materials_title_length
    check (char_length(trim(title)) between 3 and 160),
  constraint encuentro_psicologico_speaker_materials_description_length
    check (description is null or char_length(description) <= 800),
  constraint encuentro_psicologico_speaker_materials_size
    check (size_bytes > 0 and size_bytes <= 26214400)
);

create index if not exists encuentro_psicologico_speaker_materials_program_idx
  on public.encuentro_psicologico_speaker_materials (program_item_id, created_at asc);

create index if not exists encuentro_psicologico_speaker_materials_owner_idx
  on public.encuentro_psicologico_speaker_materials (owner_user_id, created_at desc);

alter table public.encuentro_psicologico_speaker_materials enable row level security;
revoke all on public.encuentro_psicologico_speaker_materials from anon, authenticated;
grant all on public.encuentro_psicologico_speaker_materials to service_role;
grant usage, select on sequence public.encuentro_psicologico_speaker_materials_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'encuentro-psicologico-speaker-materials',
  'encuentro-psicologico-speaker-materials',
  false,
  26214400,
  array[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'image/jpeg',
    'image/png'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
