create table if not exists public.encuentro_psicologico_community_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  is_default boolean not null default false,
  is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint encuentro_psicologico_community_categories_name_check check (char_length(trim(name)) between 2 and 60)
);

create table if not exists public.encuentro_psicologico_community_resources (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  category_id bigint not null references public.encuentro_psicologico_community_categories(id),
  title text not null,
  description text,
  source_author text,
  rights_basis text not null,
  responsibility_accepted_at timestamptz not null,
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  size_bytes bigint not null,
  status text not null default 'pending',
  moderation_reason text,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  removed_at timestamptz,
  constraint encuentro_psicologico_community_resources_title_check check (char_length(trim(title)) between 3 and 160),
  constraint encuentro_psicologico_community_resources_rights_check check (rights_basis in ('own_work', 'permission', 'public_domain', 'open_license', 'legal_source')),
  constraint encuentro_psicologico_community_resources_status_check check (status in ('pending', 'approved', 'rejected', 'removed')),
  constraint encuentro_psicologico_community_resources_size_check check (size_bytes > 0 and size_bytes <= 26214400)
);

create table if not exists public.encuentro_psicologico_community_downloads (
  id bigint generated by default as identity primary key,
  resource_id bigint not null references public.encuentro_psicologico_community_resources(id) on delete cascade,
  downloader_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (resource_id, downloader_user_id)
);

create table if not exists public.encuentro_psicologico_community_reward_events (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  resource_id bigint not null references public.encuentro_psicologico_community_resources(id) on delete cascade,
  event_type text not null,
  actor_user_id uuid not null references auth.users(id) on delete cascade,
  points integer not null default 1,
  created_at timestamptz not null default now(),
  constraint encuentro_psicologico_community_reward_type_check check (event_type in ('contribution', 'download')),
  constraint encuentro_psicologico_community_reward_points_check check (points = 1),
  unique (resource_id, event_type, actor_user_id)
);

insert into public.encuentro_psicologico_community_categories (name, slug, is_default)
values
  ('Libro', 'libro', true),
  ('Test', 'test', true),
  ('Cuestionario', 'cuestionario', true),
  ('Protocolo', 'protocolo', true)
on conflict (slug) do update set name = excluded.name, is_default = true, is_active = true;

create index if not exists encuentro_psicologico_community_resources_library_idx
  on public.encuentro_psicologico_community_resources (status, category_id, created_at desc);
create index if not exists encuentro_psicologico_community_resources_owner_idx
  on public.encuentro_psicologico_community_resources (owner_user_id, status, created_at desc);
create index if not exists encuentro_psicologico_community_rewards_owner_idx
  on public.encuentro_psicologico_community_reward_events (owner_user_id, created_at desc);

create or replace function public.encuentro_psicologico_community_resource_reward()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.status = 'approved' and old.status is distinct from 'approved' then
    insert into public.encuentro_psicologico_community_reward_events
      (owner_user_id, resource_id, event_type, actor_user_id)
    values (new.owner_user_id, new.id, 'contribution', new.owner_user_id)
    on conflict (resource_id, event_type, actor_user_id) do nothing;
  elsif old.status = 'approved' and new.status is distinct from 'approved' then
    delete from public.encuentro_psicologico_community_reward_events where resource_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists encuentro_psicologico_community_resource_reward_trigger
  on public.encuentro_psicologico_community_resources;
create trigger encuentro_psicologico_community_resource_reward_trigger
after update of status on public.encuentro_psicologico_community_resources
for each row execute function public.encuentro_psicologico_community_resource_reward();

create or replace function public.encuentro_psicologico_community_download_reward()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_owner uuid;
  v_status text;
begin
  select owner_user_id, status into v_owner, v_status
  from public.encuentro_psicologico_community_resources
  where id = new.resource_id;

  if v_status = 'approved' and v_owner is distinct from new.downloader_user_id then
    insert into public.encuentro_psicologico_community_reward_events
      (owner_user_id, resource_id, event_type, actor_user_id)
    values (v_owner, new.resource_id, 'download', new.downloader_user_id)
    on conflict (resource_id, event_type, actor_user_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists encuentro_psicologico_community_download_reward_trigger
  on public.encuentro_psicologico_community_downloads;
create trigger encuentro_psicologico_community_download_reward_trigger
after insert on public.encuentro_psicologico_community_downloads
for each row execute function public.encuentro_psicologico_community_download_reward();

alter table public.encuentro_psicologico_community_categories enable row level security;
alter table public.encuentro_psicologico_community_resources enable row level security;
alter table public.encuentro_psicologico_community_downloads enable row level security;
alter table public.encuentro_psicologico_community_reward_events enable row level security;

revoke all on public.encuentro_psicologico_community_categories from anon, authenticated;
revoke all on public.encuentro_psicologico_community_resources from anon, authenticated;
revoke all on public.encuentro_psicologico_community_downloads from anon, authenticated;
revoke all on public.encuentro_psicologico_community_reward_events from anon, authenticated;
grant all on public.encuentro_psicologico_community_categories to service_role;
grant all on public.encuentro_psicologico_community_resources to service_role;
grant all on public.encuentro_psicologico_community_downloads to service_role;
grant all on public.encuentro_psicologico_community_reward_events to service_role;
grant usage, select on sequence public.encuentro_psicologico_community_categories_id_seq to service_role;
grant usage, select on sequence public.encuentro_psicologico_community_resources_id_seq to service_role;
grant usage, select on sequence public.encuentro_psicologico_community_downloads_id_seq to service_role;
grant usage, select on sequence public.encuentro_psicologico_community_reward_events_id_seq to service_role;

revoke all on function public.encuentro_psicologico_community_resource_reward() from public, anon, authenticated;
revoke all on function public.encuentro_psicologico_community_download_reward() from public, anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'encuentro-psicologico-community-resources',
  'encuentro-psicologico-community-resources',
  false,
  26214400,
  array[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'image/jpeg',
    'image/png'
  ]
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
