alter table public.encuentro_psicologico_registrations add column if not exists department text;
alter table public.encuentro_psicologico_profiles add column if not exists department text;

create table if not exists public.encuentro_psicologico_support_issues (
  id bigint generated by default as identity primary key,
  phone text not null,
  problem text not null,
  status text not null default 'open' check (status in ('open', 'resolved')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

alter table public.encuentro_psicologico_support_issues enable row level security;
revoke all on public.encuentro_psicologico_support_issues from anon, authenticated;
grant all on public.encuentro_psicologico_support_issues to service_role;
grant usage, select on sequence public.encuentro_psicologico_support_issues_id_seq to service_role;

create index if not exists encuentro_psicologico_support_issues_status_idx
  on public.encuentro_psicologico_support_issues (status, created_at desc);

create or replace function public.encuentro_psicologico_mask_email(p_email text)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_local text;
  v_domain text;
  v_domain_name text;
  v_domain_tld text;
begin
  if p_email is null or position('@' in p_email) = 0 then return null; end if;
  v_local := split_part(p_email, '@', 1);
  v_domain := split_part(p_email, '@', 2);
  v_domain_name := split_part(v_domain, '.', 1);
  v_domain_tld := substring(v_domain from position('.' in v_domain));
  return left(v_local, 2) || repeat('*', greatest(2, length(v_local) - 3)) || right(v_local, 1) || '@' || left(v_domain_name, 1) || repeat('*', greatest(2, length(v_domain_name) - 2)) || right(v_domain_name, 1) || v_domain_tld;
end;
$$;

revoke all on function public.encuentro_psicologico_mask_email(text) from public, anon, authenticated;
grant execute on function public.encuentro_psicologico_mask_email(text) to service_role;

create or replace function public.encuentro_psicologico_lookup_by_phone(p_phone text)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_phone text := regexp_replace(coalesce(p_phone, ''), '[^0-9]', '', 'g');
  v_user_id uuid;
  v_email text;
  v_modality text;
  v_status text;
begin
  select p.user_id, u.email into v_user_id, v_email
  from public.encuentro_psicologico_profiles p
  join auth.users u on u.id = p.user_id
  where regexp_replace(p.phone, '[^0-9]', '', 'g') = v_phone
  order by p.created_at desc
  limit 1;

  if v_user_id is null then
    select r.user_id, r.email into v_user_id, v_email
    from public.encuentro_psicologico_registrations r
    where regexp_replace(r.phone, '[^0-9]', '', 'g') = v_phone
      and r.status in ('confirmed', 'waitlist')
    order by r.created_at desc
    limit 1;
  end if;

  if v_email is null then
    return jsonb_build_object('found', false);
  end if;

  select modality, status into v_modality, v_status
  from public.encuentro_psicologico_registrations
  where regexp_replace(phone, '[^0-9]', '', 'g') = v_phone
    and status in ('confirmed', 'waitlist')
  order by created_at desc
  limit 1;

  return jsonb_build_object('found', true, 'maskedEmail', public.encuentro_psicologico_mask_email(v_email), 'modality', v_modality, 'status', v_status);
end;
$$;

revoke all on function public.encuentro_psicologico_lookup_by_phone(text) from public, anon, authenticated;
grant execute on function public.encuentro_psicologico_lookup_by_phone(text) to service_role;

create or replace function public.encuentro_psicologico_auth_user_id_by_phone_email(p_phone text, p_email text)
returns uuid
language sql
security definer
set search_path = public, auth, pg_temp
as $$
  select p.user_id
  from public.encuentro_psicologico_profiles p
  join auth.users u on u.id = p.user_id
  where regexp_replace(p.phone, '[^0-9]', '', 'g') = regexp_replace(coalesce(p_phone, ''), '[^0-9]', '', 'g')
    and lower(u.email) = lower(trim(p_email))
  order by p.created_at desc
  limit 1
$$;

revoke all on function public.encuentro_psicologico_auth_user_id_by_phone_email(text,text) from public, anon, authenticated;
grant execute on function public.encuentro_psicologico_auth_user_id_by_phone_email(text,text) to service_role;

create or replace function public.encuentro_psicologico_register(
  p_modality text,
  p_name text,
  p_email text,
  p_phone text,
  p_attendee_type text default 'general',
  p_profession text default null,
  p_license text default null,
  p_institution text default null,
  p_country text default 'Guatemala',
  p_waitlist boolean default false,
  p_user_id uuid default null,
  p_department text default null
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_confirmed integer;
  v_status text;
  v_existing_status text;
begin
  if p_modality not in ('presencial', 'virtual') then
    raise exception 'Modalidad invalida';
  end if;

  select status into v_existing_status
  from public.encuentro_psicologico_registrations
  where lower(email) = lower(trim(p_email))
    and modality = p_modality
    and status in ('confirmed', 'waitlist')
  order by created_at desc
  limit 1;

  if v_existing_status is not null then
    select count(*) into v_confirmed
    from public.encuentro_psicologico_registrations
    where modality = 'presencial' and status = 'confirmed';

    return jsonb_build_object('status', 'already_registered', 'registration_status', v_existing_status, 'available', greatest(0, 250 - v_confirmed));
  end if;

  perform pg_advisory_xact_lock(hashtext('encuentro_psicologico_capacity'));
  select count(*) into v_confirmed
  from public.encuentro_psicologico_registrations
  where modality = 'presencial' and status = 'confirmed';

  if p_modality = 'presencial' and v_confirmed >= 250 and not p_waitlist then
    return jsonb_build_object('status', 'full', 'available', 0);
  end if;

  v_status := case when p_modality = 'presencial' and (p_waitlist or v_confirmed >= 250) then 'waitlist' else 'confirmed' end;

  insert into public.encuentro_psicologico_registrations
    (modality, name, email, phone, attendee_type, profession, license, institution, country, department, status, user_id)
  values
    (p_modality, p_name, lower(trim(p_email)), regexp_replace(p_phone, '[^0-9]', '', 'g'), p_attendee_type, p_profession, regexp_replace(coalesce(p_license, ''), '[^0-9]', '', 'g'), p_institution, p_country, p_department, v_status, p_user_id);

  if p_user_id is not null then
    insert into public.encuentro_psicologico_profiles
      (user_id, full_name, phone, attendee_type, profession, license, institution, country, department)
    values
      (p_user_id, p_name, regexp_replace(p_phone, '[^0-9]', '', 'g'), p_attendee_type, p_profession, regexp_replace(coalesce(p_license, ''), '[^0-9]', '', 'g'), p_institution, coalesce(nullif(p_country, ''), 'Guatemala'), p_department)
    on conflict (user_id) do update set
      full_name = excluded.full_name,
      phone = excluded.phone,
      attendee_type = excluded.attendee_type,
      profession = excluded.profession,
      license = excluded.license,
      institution = excluded.institution,
      country = excluded.country,
      department = excluded.department,
      updated_at = now();

    insert into public.encuentro_psicologico_certificates (user_id)
    values (p_user_id)
    on conflict (user_id) do nothing;
  end if;

  if p_modality = 'presencial' and v_status = 'confirmed' then
    v_confirmed := v_confirmed + 1;
  end if;

  return jsonb_build_object('status', v_status, 'available', greatest(0, 250 - v_confirmed));
end;
$$;

revoke all on function public.encuentro_psicologico_register(text,text,text,text,text,text,text,text,text,boolean,uuid,text) from public, anon, authenticated;
grant execute on function public.encuentro_psicologico_register(text,text,text,text,text,text,text,text,text,boolean,uuid,text) to service_role;

create or replace function public.encuentro_psicologico_switch_presencial_to_virtual(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_confirmed integer;
  v_registration record;
begin
  perform pg_advisory_xact_lock(hashtext('encuentro_psicologico_capacity'));
  select count(*) into v_confirmed
  from public.encuentro_psicologico_registrations
  where modality = 'presencial' and status = 'confirmed';

  if v_confirmed < 250 then
    return jsonb_build_object('status', 'not_available', 'available', greatest(0, 250 - v_confirmed));
  end if;

  select * into v_registration
  from public.encuentro_psicologico_registrations
  where user_id = p_user_id and modality = 'presencial' and status = 'confirmed'
  order by created_at desc
  limit 1;

  if v_registration.id is null then
    return jsonb_build_object('status', 'not_found', 'available', greatest(0, 250 - v_confirmed));
  end if;

  if exists (select 1 from public.encuentro_psicologico_registrations where user_id = p_user_id and modality = 'virtual' and status in ('confirmed', 'waitlist')) then
    update public.encuentro_psicologico_registrations set status = 'cancelled' where id = v_registration.id;
    return jsonb_build_object('status', 'already_virtual', 'available', 1);
  end if;

  update public.encuentro_psicologico_registrations
  set modality = 'virtual', status = 'confirmed'
  where id = v_registration.id;

  return jsonb_build_object('status', 'switched', 'available', 1);
end;
$$;

revoke all on function public.encuentro_psicologico_switch_presencial_to_virtual(uuid) from public, anon, authenticated;
grant execute on function public.encuentro_psicologico_switch_presencial_to_virtual(uuid) to service_role;
