create table if not exists public.encuentro_psicologico_registrations (
  id bigint generated by default as identity primary key,
  modality text not null check (modality in ('presencial', 'virtual')),
  name text not null,
  email text not null,
  phone text not null,
  attendee_type text not null default 'general',
  profession text,
  license text,
  institution text,
  country text not null default 'Guatemala',
  status text not null check (status in ('confirmed', 'waitlist', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists encuentro_psicologico_registrations_capacity_idx
  on public.encuentro_psicologico_registrations (modality, status);

alter table public.encuentro_psicologico_registrations enable row level security;
create policy "encuentro_psicologico_registrations_server_only"
  on public.encuentro_psicologico_registrations for all to anon, authenticated
  using (false) with check (false);
revoke all on table public.encuentro_psicologico_registrations from anon, authenticated;
grant all on table public.encuentro_psicologico_registrations to service_role;
grant usage, select on sequence public.encuentro_psicologico_registrations_id_seq to service_role;

create table if not exists public.encuentro_psicologico_content (
  id text primary key,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.encuentro_psicologico_content enable row level security;
create policy "encuentro_psicologico_content_server_only"
  on public.encuentro_psicologico_content for all to anon, authenticated
  using (false) with check (false);
revoke all on table public.encuentro_psicologico_content from anon, authenticated;
grant all on table public.encuentro_psicologico_content to service_role;

create or replace function public.encuentro_psicologico_register(
  p_modality text,
  p_name text,
  p_email text,
  p_phone text,
  p_attendee_type text default 'general',
  p_profession text default null,
  p_license text default null,
  p_institution text default null,
  p_country text default 'Guatemala',
  p_waitlist boolean default false
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_confirmed integer;
  v_status text;
begin
  if p_modality not in ('presencial', 'virtual') then
    raise exception 'Modalidad inválida';
  end if;

  perform pg_advisory_xact_lock(hashtext('encuentro_psicologico_capacity'));
  select count(*) into v_confirmed
  from public.encuentro_psicologico_registrations
  where modality = 'presencial' and status = 'confirmed';

  if p_modality = 'presencial' and v_confirmed >= 250 and not p_waitlist then
    return jsonb_build_object('status', 'full', 'available', 0);
  end if;

  v_status := case
    when p_modality = 'presencial' and (p_waitlist or v_confirmed >= 250) then 'waitlist'
    else 'confirmed'
  end;

  insert into public.encuentro_psicologico_registrations
    (modality, name, email, phone, attendee_type, profession, license, institution, country, status)
  values
    (p_modality, p_name, lower(trim(p_email)), p_phone, p_attendee_type, p_profession, p_license, p_institution, p_country, v_status);

  if p_modality = 'presencial' and v_status = 'confirmed' then v_confirmed := v_confirmed + 1; end if;
  return jsonb_build_object('status', v_status, 'available', greatest(0, 250 - v_confirmed));
end;
$$;

revoke all on function public.encuentro_psicologico_register(text,text,text,text,text,text,text,text,text,boolean) from public, anon, authenticated;
grant execute on function public.encuentro_psicologico_register(text,text,text,text,text,text,text,text,text,boolean) to service_role;
