-- Operational tools for the Encuentro Clínico de Psicología.
-- Every record remains under the event-specific namespace so it never shares
-- participant data or permissions with the other applications in this project.

alter table public.encuentro_psicologico_registrations
  add column if not exists gender text,
  add column if not exists event_roles text[] not null default '{}'::text[],
  add column if not exists speaker_program_item_id bigint references public.encuentro_psicologico_program(id) on delete set null;

alter table public.encuentro_psicologico_profiles
  add column if not exists gender text,
  add column if not exists event_roles text[] not null default '{}'::text[];

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'encuentro_psicologico_registrations_gender_check') then
    alter table public.encuentro_psicologico_registrations
      add constraint encuentro_psicologico_registrations_gender_check check (gender is null or gender in ('Hombre', 'Mujer'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'encuentro_psicologico_profiles_gender_check') then
    alter table public.encuentro_psicologico_profiles
      add constraint encuentro_psicologico_profiles_gender_check check (gender is null or gender in ('Hombre', 'Mujer'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'encuentro_psicologico_registrations_event_roles_check') then
    alter table public.encuentro_psicologico_registrations
      add constraint encuentro_psicologico_registrations_event_roles_check check (event_roles <@ array['speaker', 'organizer']::text[]);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'encuentro_psicologico_profiles_event_roles_check') then
    alter table public.encuentro_psicologico_profiles
      add constraint encuentro_psicologico_profiles_event_roles_check check (event_roles <@ array['speaker', 'organizer']::text[]);
  end if;
end $$;

create index if not exists encuentro_psicologico_registrations_department_idx
  on public.encuentro_psicologico_registrations (department, status);
create index if not exists encuentro_psicologico_registrations_roles_idx
  on public.encuentro_psicologico_registrations using gin (event_roles);
create unique index if not exists encuentro_psicologico_one_speaker_per_program_idx
  on public.encuentro_psicologico_registrations (speaker_program_item_id)
  where speaker_program_item_id is not null and event_roles @> array['speaker']::text[];

alter table public.encuentro_psicologico_certificates
  add column if not exists certificate_type text not null default 'general',
  add column if not exists template_snapshot jsonb not null default '{}'::jsonb;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'encuentro_psicologico_certificates_type_check') then
    alter table public.encuentro_psicologico_certificates
      add constraint encuentro_psicologico_certificates_type_check check (certificate_type in ('professional', 'general'));
  end if;
end $$;

create table if not exists public.encuentro_psicologico_certificate_settings (
  id boolean primary key default true check (id),
  event_name text not null default 'Cuando el Duelo se Detiene: Jornada Clínica sobre Duelo Prolongado',
  event_date text not null default '15 de agosto de 2026',
  event_place text not null default 'Chimaltenango, Guatemala',
  professional_title text not null default 'Diploma de participación profesional',
  general_title text not null default 'Diploma de participación',
  professional_body text not null default 'Por su valiosa participación y actualización profesional en la jornada clínica.',
  general_body text not null default 'Por su valiosa participación en la jornada clínica.',
  signatures jsonb not null default '[{"name":"","role":"","image_url":""},{"name":"","role":"","image_url":""}]'::jsonb,
  sponsor_logos jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.encuentro_psicologico_certificate_settings (id)
values (true)
on conflict (id) do nothing;

create table if not exists public.encuentro_psicologico_event_settings (
  id boolean primary key default true check (id),
  questions_enabled boolean not null default false,
  updated_at timestamptz not null default now()
);

insert into public.encuentro_psicologico_event_settings (id)
values (true)
on conflict (id) do nothing;

create table if not exists public.encuentro_psicologico_speaker_questions (
  id bigint generated by default as identity primary key,
  asker_user_id uuid not null references auth.users(id) on delete cascade,
  speaker_user_id uuid not null references auth.users(id) on delete cascade,
  program_item_id bigint not null references public.encuentro_psicologico_program(id) on delete cascade,
  question text not null,
  speaker_rating smallint not null default 5 check (speaker_rating between 1 and 5),
  event_rating smallint not null default 5 check (event_rating between 1 and 5),
  is_favorite boolean not null default false,
  favorited_at timestamptz,
  created_at timestamptz not null default now(),
  constraint encuentro_psicologico_speaker_questions_length check (char_length(trim(question)) between 5 and 1400)
);

create index if not exists encuentro_psicologico_speaker_questions_inbox_idx
  on public.encuentro_psicologico_speaker_questions (speaker_user_id, is_favorite desc, created_at asc);
create index if not exists encuentro_psicologico_speaker_questions_program_idx
  on public.encuentro_psicologico_speaker_questions (program_item_id, created_at desc);
create index if not exists encuentro_psicologico_speaker_questions_asker_idx
  on public.encuentro_psicologico_speaker_questions (asker_user_id, created_at desc);

alter table public.encuentro_psicologico_certificate_settings enable row level security;
alter table public.encuentro_psicologico_event_settings enable row level security;
alter table public.encuentro_psicologico_speaker_questions enable row level security;

revoke all on public.encuentro_psicologico_certificate_settings from anon, authenticated;
revoke all on public.encuentro_psicologico_event_settings from anon, authenticated;
revoke all on public.encuentro_psicologico_speaker_questions from anon, authenticated;
grant all on public.encuentro_psicologico_certificate_settings to service_role;
grant all on public.encuentro_psicologico_event_settings to service_role;
grant all on public.encuentro_psicologico_speaker_questions to service_role;
grant usage, select on sequence public.encuentro_psicologico_speaker_questions_id_seq to service_role;
