create table if not exists public.encuentro_psicologico_speakers (
  id bigint generated by default as identity primary key,
  name text not null,
  professional_title text not null default '',
  talk_title text not null default '',
  talk_time text not null default '',
  bio text not null default '',
  photo_url text,
  video_url text,
  display_order integer not null default 0,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint encuentro_psicologico_speakers_name_length check (char_length(name) between 2 and 160),
  constraint encuentro_psicologico_speakers_order_nonnegative check (display_order >= 0)
);

alter table public.encuentro_psicologico_speakers enable row level security;
revoke all on table public.encuentro_psicologico_speakers from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('encuentro-psicologico-media', 'encuentro-psicologico-media', true, 52428800, array['image/jpeg','image/png','image/webp','video/mp4','video/webm'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
